### ISSUE TITLE
Some usability issues (may be duplicates of existing issues)

### ISSUE THREAD

**Issue by alexeyza** [CFedderly/bumerang-client#141]
Thank you for sending the link to download the app, it was actually very simple to install it from Google Play.

And I understand that it is beta, and you're working on it. I just thought I'll mention some issues I encountered - **it doesn't mean they should be high priority** (deal with them as you see fit).

1. Right after logging in with Facebook, the app gave me an error:
![screenshot_20161124-114357](https://cloud.githubusercontent.com/assets/1856224/20609108/62827bae-b23d-11e6-98f4-5e98e89276c1.png)
So some users may give up. However, when I run it again, it seems to work fine.

2. The first screen I see (as a user) is the profile creation screen. Some users may be a bit intimitated by the profile screen, and perhaps landing them in the "browse" screen is better? What do you think? This may not be an issue.
![screenshot_20161124-114445](https://cloud.githubusercontent.com/assets/1856224/20609161/edeaa0fe-b23d-11e6-9f76-433c75d08f2c.png)

3. As a user, I have no idea what the number 10 on the profile screen means. I guess it can be the number of friends I have??

4. The interface is very smooth, and the UI design seems intuitive.
![screenshot_20161124-120639](https://cloud.githubusercontent.com/assets/1856224/20609229/90dec182-b23e-11e6-8915-c56b22454d6b.png)

5. The app showed me a "app crashed" screen after some playing around, though the app was still working (from the user perspective).

**Comment by CFedderly** [comment]
Thanks for the feedback, @alexeyza. We're going to make it more clear what the number on the profile page means (it's your karma), since that's feedback we've received from other users. We're also currently working on the login bug that you noticed. Thanks for checking it out!
