### ISSUE TITLE
Analytics tracking

### ISSUE THREAD

**Issue by bjschnell** [CFedderly/bumerang-client#59]
Discuss with mentors about what they feel appropriate analytics use are. Implement analytics accordingly to properly update.

**Comment by alexeyza** [comment]
What do you mean "what appropriate analytics are"? Do you mean what things should you measure?

**Comment by bjschnell** [comment]
@alexeyza Yes, it was about what things we should be measuring. We plan to discuss this with the mentors at a later date as it is not necessary for Milestone 2

**Comment by alexeyza** [comment]
OK, great.

Here is something basic to get you started on this:
[Metrics.pdf](https://github.com/CFedderly/bumerang-client/files/563202/Metrics.pdf)
