### ISSUE TITLE
Clearly define and document standard usage of App.

### ISSUE THREAD

**Issue by bjschnell** [CFedderly/bumerang-client#66]
We need to clearly define user interaction with the application, define expected behaviour and transitions between screens and record defined application behaviour for better clarity of the system specifications. Define expected output when a user performs certain tasks. For example, When a user accepts a request, what screen are they re-directed to? what changes in the application? Are there other places that must update as well to reflect the user accepting the request?

**Comment by bjschnell** [comment]
There are four main scenarios. Lending with no pending accepts, borrow with no pending accepts, Lend with a pending request, and borrowing with a pending request.

**Comment by bjschnell** [comment]
Connor and Daniel have the notes for the main use case as of Oct 31 2016.

**Comment by connerleverett** [comment]
Scenario 1 Charlotte wants to borrow a pencil:
1) Charlotte creates a request and sees the request in the "I want to borrow" tab in My Requests.
2) Brady sees the request in the "I want to lend" on the browse page.
3) Brady clicks on the request, and sees Charlotte's profile picture and her Karma. Brady accepts the request.
4) Charlotte get a notification. When she clicks on the notification, it takes her to the "I want to borrow" tab in her "My Requests". When she clicks on her request, it shows Brady's profile (picture and karma). If she accepts she then gets Brady's phone number and can begin the interaction.
5) The 'list item' is put in the the 'pending page'. In Brady's the 'list item' is blue and says he is lending this item. In Charlotte's 'pending page' the 'list item' is pink and says she is borrowing the item.

Scenario 2 Brady wants to give anyone his pencil e.g he is offering his pencil to the world
1) Brady makes a 'request' in the create request page and marks the 'lend' tab. 
2) Daniel sees it in the "I want to borrow" tab on browse page. When Daniel clicks it Brady is sent a notification
3) Brady sees the notification which shows Daniel's picture and karma. He accepts the notification which says that he will lend his pencil to Daniel. He gets Daniel's phone number.
4) The pending section of both Daniel and Brady's page is updated. Brady's pending has a blue item as he is lending the item. Daniel has a pink item as he is borrowing the item.
